alter table sturwild.capture_etat rename column capture_etat_id to capture_state_id;
alter table sturwild.capture_etat rename column capture_etat_libelle to capture_state_name;
alter table sturwild.capture_mode rename column capture_mode_id to capture_method_id;
alter table sturwild.capture_mode rename column capture_mode_libelle to capture_method_name;
alter table sturwild.capture_type rename column capture_type_id to origin_id;
alter table sturwild.capture_type rename column capture_type_libelle to origin_name;
alter table sturwild.ciem rename column ciem_id to ices_id;
alter table sturwild.ciem rename column ciem_libelle to ices_name;
comment on column sturwild.dbversion.dbversion_number is E'Number of the version';
comment on column sturwild.dbversion.dbversion_date is E'Date of the version';
comment on column sturwild.declaration.declaration_id is E'Identifier of the capture';
alter table sturwild.declaration rename column statut_id to status_id;
alter table sturwild.declaration rename column capture_mode_id to capture_method_id;
alter table sturwild.declaration rename column capture_type_id to origin_id;
alter table sturwild.declaration rename column engin_type_id to gear_type_id;
comment on column sturwild.declaration.espece_id is E'Species identifier';
alter table sturwild.declaration rename column espece_id to species_id;
alter table sturwild.declaration rename column capture_etat_id to capture_state_id;
alter table sturwild.declaration rename column devenir_id to fate_id;
comment on column sturwild.declaration.capture_date is E'Date of the capture';
comment on column sturwild.declaration.annee is E'Fishing year';
alter table sturwild.declaration rename column annee to year;
alter table sturwild.declaration rename column nombre_capture to caught_number;
comment on column sturwild.declaration.capture_date_estimee is E'Estimation of capture date';
alter table sturwild.declaration rename column capture_date_estimee to estimated_capture_date;
comment on column sturwild.declaration.engin_maille is E'Mesh size, if applicable';
alter table sturwild.declaration rename column engin_maille to gear_mesh;
comment on column sturwild.declaration.espece_ciblee is E'Species normally targeted during fishing';
alter table sturwild.declaration rename column espece_ciblee to target_species;
comment on column sturwild.declaration.profondeur is E'Fishing depth, in meters';
alter table sturwild.declaration rename column profondeur to depth;
comment on column sturwild.declaration.prof_min is E'Minimum fishing depth, in meters';
alter table sturwild.declaration rename column prof_min to depth_min;
comment on column sturwild.declaration.prof_max is E'Maximum fishing depth, in meters';
alter table sturwild.declaration rename column prof_max to depth_max;
comment on column sturwild.declaration.lt_min is E'Minimum length, in mm';
alter table sturwild.declaration rename column lt_min to length_min;
comment on column sturwild.declaration.lt_max is E'Maximum length, in mm';
alter table sturwild.declaration rename column lt_max to length_max;
comment on column sturwild.declaration.masse_min is E'Minimum weight, in kg';
alter table sturwild.declaration rename column masse_min to weight_min;
comment on column sturwild.declaration.masse_max is E'Maximum weight, in kg';
alter table sturwild.declaration rename column masse_max to weight_max;
comment on column sturwild.declaration.pecheur_code is E'fisher’s code';
alter table sturwild.declaration rename column pecheur_code to fisher_code;
comment on column sturwild.declaration.interlocuteur is E'Other contact';
alter table sturwild.declaration rename column interlocuteur to contact;
comment on column sturwild.declaration.interlocuteur_coord is E'Coordonates of the other contact';
alter table sturwild.declaration rename column interlocuteur_coord to contact_coordonates;
comment on column sturwild.declaration.navire_port is E'Home harbour of fishing vessel';
alter table sturwild.declaration rename column navire_port to harbour_vessel;
comment on column sturwild.declaration.observation is E'General remarks';
alter table sturwild.declaration rename column observation to remarks;
comment on column sturwild.declaration.manipulation is E'Post-capture handling of the captured batch';
alter table sturwild.declaration rename column manipulation to handling;
comment on column sturwild.declaration.qualite_identification is E'0: species identification uncertain
1: identification certain';
alter table sturwild.declaration rename column qualite_identification to identification_quality;
alter table sturwild.devenir rename column devenir_id to fate_id;
alter table sturwild.devenir rename column devenir_libelle to fate_name;
comment on column sturwild.document.document_nom is E'Original name of the document';
alter table sturwild.document rename column document_nom to document_name;
comment on column sturwild.document.document_description is E'Description of the document';
alter table sturwild.document rename column individu_id to fish_id;
alter table sturwild.engin_type rename column engin_type_id to gear_type_id;
alter table sturwild.engin_type rename column engin_type_libelle to gear_type_name;
comment on column sturwild.espece.espece_id is E'Identifier of the species';
alter table sturwild.espece rename column espece_id to species_id;
comment on column sturwild.espece.espece_libelle is E'Name of the spieces';
alter table sturwild.espece rename column espece_libelle to species_name;
alter table sturwild.evenement rename column evenement_id to event_id;
alter table sturwild.evenement rename column evenement_type_id to event_type_id;
alter table sturwild.evenement rename column evenement_date to event_date;
comment on column sturwild.evenement.evenement_commentaire is E'remarks on the event';
alter table sturwild.evenement rename column evenement_commentaire to event_remarks;
comment on column sturwild.evenement.login is E'Login of the person who created the event';
alter table sturwild.evenement_type rename column evenement_type_id to event_type_id;
alter table sturwild.evenement_type rename column evenement_type_libelle to event_type_name;
alter table sturwild.individu rename column individu_id to fish_id;
comment on column sturwild.individu.declaration_id is E'Identifier of the declaration';
alter table sturwild.individu rename column espece_id to species_id;
alter table sturwild.individu rename column presence_marque_id to tag_presence_id;
alter table sturwild.individu rename column capture_etat_id to capture_state_id;
alter table sturwild.individu rename column devenir_id to fate_id;
comment on column sturwild.individu.masse is E'weitgh of the fish caught, in grams';
alter table sturwild.individu rename column masse to weight;
comment on column sturwild.individu.manipulation is E'Post-capture handling';
alter table sturwild.individu rename column manipulation to handling;
alter table sturwild.individu rename column numero_marque to tag_number;
comment on column sturwild.individu.longueur_individu is E'Length of the fish, in mm';
alter table sturwild.individu rename column longueur_individu to fish_length;
comment on column sturwild.individu.cohorte_estimee is E'Estimated cohort (year of birth)';
alter table sturwild.individu rename column cohorte_estimee to estimated_cohort;
comment on column sturwild.individu.cohorte_validee is E'Validated cohort by expert opinion (year of birth)';
alter table sturwild.individu rename column cohorte_validee to validated_cohort;
comment on column sturwild.individu.historique is E'Background of the fish';
alter table sturwild.individu rename column historique to background;
comment on column sturwild.individu.commentaire is E'General remarks on the fish (general state, etc.)';
alter table sturwild.individu rename column commentaire to remarks;
comment on column sturwild.individu.qualite_identification is E'0: species identification uncertain
1: identification certain';
alter table sturwild.individu rename column qualite_identification to identification_quality;
alter table sturwild.localisation rename column pays_id to country_id;
alter table sturwild.localisation rename column ciem_id to ices_id;
alter table sturwild.localisation rename column milieu_id to environment_id;
alter table sturwild.localisation rename column zone_detail to area_detail;
comment on column sturwild.localisation.longitude_gps is E'Longitude in degree, minute, second';
comment on column sturwild.localisation.latitude_gps is E'Latitude in degree, minute, second';
comment on column sturwild.localisation.longitude_declaree_dd is E'Declared longitude, in decimal format';
alter table sturwild.localisation rename column longitude_declaree_dd to longitude_declared_dd;
comment on column sturwild.localisation.latitude_declaree_dd is E'Declared latitude, in decimal format';
alter table sturwild.localisation rename column latitude_declaree_dd to latitude_declared_dd;
comment on column sturwild.localisation.longitude_estimee_dd is E'Estimated longitude, in decimal format';
alter table sturwild.localisation rename column longitude_estimee_dd to longitude_estimated_dd;
comment on column sturwild.localisation.latitude_estimee_dd is E'Estimated latitude, in decimal format';
alter table sturwild.localisation rename column latitude_estimee_dd to latitude_estimated_dd;
comment on column sturwild.localisation.longitude_dd is E'Used longitude, in decimal format';
comment on column sturwild.localisation.latitude_dd is E'used latitude, in decimal format';
alter table sturwild.localisation rename column precision_id to accuracy_id;
alter table sturwild.localisation rename column milieu_detail_id to environment_detail_id;
comment on column sturwild.milieu.milieu_id is E'Identifier of the environment';
alter table sturwild.milieu rename column milieu_id to environment_id;
comment on column sturwild.milieu.milieu_libelle is E'Name of the environment';
alter table sturwild.milieu rename column milieu_libelle to environment_name;
alter table sturwild.milieu_detail rename column milieu_detail_id to environment_detail_id;
alter table sturwild.milieu_detail rename column milieu_detail_libelle to environment_detail_name;
comment on column sturwild.mime_type.content_type is E'Official mime type';
comment on column sturwild.mime_type.extension is E'File extension';
comment on column sturwild.pays.pays_id is E'Identifier of the country';
alter table sturwild.pays rename column pays_id to country_id;
alter table sturwild.pays rename column pays_libelle to country_name;
comment on column sturwild.pays.pays_order is E'Order of display in the application';
alter table sturwild.pays rename column pays_order to country_order;
alter table sturwild.precision rename column precision_id to accuracy_id;
alter table sturwild.precision rename column precision_name to accuracy_name;
alter table sturwild.presence_marque rename column presence_marque_id to tag_presence_id;
alter table sturwild.presence_marque rename column presence_marque_libelle to tag_presence_name;
comment on column sturwild.request.body is E'Body of the request';
alter table sturwild.statut rename column statut_id to status_id;
alter table sturwild.statut rename column statut_libelle to status_name;
comment on table sturwild.capture_etat is E'Table of capture status';
alter table sturwild.capture_etat rename to capture_state;
alter sequence if exists sturwild.capture_etat_capture_etat_id_seq rename to capture_state_capture_state_id_seq;
comment on table sturwild.capture_mode is E'Method of capturing fish';
alter table sturwild.capture_mode rename to capture_method;
alter sequence if exists sturwild.capture_mode_capture_mode_id_seq rename to capture_method_capture_method_id_seq;
comment on table sturwild.capture_type is E'Origin of the capture (commercial, recreational, scientific)';
alter table sturwild.capture_type rename to origin;
alter sequence if exists sturwild.capture_type_capture_type_id_seq rename to origin_origin_id_seq;
comment on table sturwild.ciem is E'Table of ICES fishing zones';
alter table sturwild.ciem rename to ices;
alter sequence if exists sturwild.ciem_ciem_id_seq rename to ices_ices_id_seq;
comment on table sturwild.dbversion is E'Table of database versions';
comment on table sturwild.declaration is E'Information relating to the declaration';
comment on table sturwild.devenir is E'Fate of sturgeon caught';
alter table sturwild.devenir rename to fate;
alter sequence if exists sturwild.devenir_devenir_id_seq rename to fate_fate_id_seq;
comment on table sturwild.document is E'Numeric documents relating to a fish or an event';
comment on table sturwild.engin_type is E'Table of gears';
alter table sturwild.engin_type rename to gear_type;
alter sequence if exists sturwild.engin_type_engin_type_id_seq rename to gear_type_gear_type_id_seq;
alter table sturwild.espece rename to species;
alter sequence if exists sturwild.espece_espece_id_seq rename to species_species_id_seq;
alter table sturwild.estuaire_area rename to estuary_area;
alter sequence if exists sturwild.estuaire_area_estuaire_area_id_seq rename to estuary_area_estuary_area_id_seq;
alter table sturwild.evenement rename to event;
alter sequence if exists sturwild.evenement_evenement_id_seq rename to event_event_id_seq;
comment on table sturwild.evenement_type is E'Types of possible events on a declaration';
alter table sturwild.evenement_type rename to event_type;
alter sequence if exists sturwild.evenement_type_evenement_type_id_seq rename to event_type_event_type_id_seq;
alter table sturwild.individu rename to fish;
alter sequence if exists sturwild.individu_individu_id_seq rename to fish_fish_id_seq;
alter table sturwild.localisation rename to location;
alter sequence if exists sturwild.localisation_localisation_id_seq rename to location_location_id_seq;
comment on table sturwild.milieu is E'Table of environment';
alter table sturwild.milieu rename to environment;
alter sequence if exists sturwild.milieu_milieu_id_seq rename to environment_environment_id_seq;
comment on table sturwild.milieu_detail is E'Environment detail';
alter table sturwild.milieu_detail rename to environment_detail;
alter sequence if exists sturwild.milieu_detail_milieu_detail_id_seq rename to environment_detail_environment_detail_id_seq;
comment on table sturwild.mime_type is E'Table of mime types for associated documents';
comment on table sturwild.pays is E'Fishing country';
alter table sturwild.pays rename to country;
alter sequence if exists sturwild.pays_pays_id_seq rename to country_country_id_seq;
comment on table sturwild.precision is E'Accuracy of GPS point location';
alter table sturwild.precision rename to accuracy;
alter sequence if exists sturwild.precision_precision_id_seq rename to accuracy_accuracy_id_seq;
comment on table sturwild.presence_marque is E'Table of tag presence types (present, not indicated, absent)';
alter table sturwild.presence_marque rename to tag_presence;
alter sequence if exists sturwild.presence_marque_presence_marque_id_seq rename to tag_presence_tag_presence_id_seq;
comment on table sturwild.statut is E'Declaration status table';
alter table sturwild.statut rename to status;
alter sequence if exists sturwild.statut_statut_id_seq rename to status_status_id_seq;
drop table sturwild.region cascade;
